version: "3.8"

services:
  mongodb:
    image: mongo:6.0.2-focal
  nodejs-app-test:
    build: .
    entrypoint: npm test
    volumes:
      - ./test:/usr/src/app/test
      - ./src:/usr/src/app/src
      - ./.mocharc.js:/usr/src/app/.mocharc.js
    depends_on:
      - mongodb

