image: docker:20.10.13

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"

services:
  - docker:20.10.13-dind

stages:
  - test

before_script:
  - apk add docker-cli-compose

test-mongo:
  stage: test
  script:
    - cd 01-mongodb
    - docker compose run --rm nodejs-app-test

test-kafka:
  stage: test
  script:
    - cd 02-kafka
    - docker compose run --rm nodejs-app-test