image: docker:20.10.13

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"

services:
  - docker:20.10.13-dind

stages:
  - test-mongo

test-mongo:
  stage: test-mongo
  script:
    - apk add docker-cli-compose
    - echo "Running tests..."
    - cd 01-mongodb
    - docker compose run --rm nodejs-app-test